DEMO_MINE_ID = "MINE-03"
DEMO_MINE_NAME = "Demo Mine 03"
DEMO_AREA_NAME = "Jharia Area"

MANAGER_ID = "USR-MSHARMA"
MANAGER_EMPLOYEE_CODE = "CIL-MGR-003"
MANAGER_NAME = "M. Sharma"
MANAGER_ROLE = "Safety Officer"

REPORTER_ID = "USR-RKUMAR"
REPORTER_EMPLOYEE_CODE = "CIL-SRD-014"
REPORTER_NAME = "Rajesh Kumar (Sirdar)"
REPORTER_ROLE = "Sirdar"

HERO_HAZARD_ID = "HZRD-2026-442"
HERO_HAZARD_TITLE = "Roof support damage observed"
HERO_HAZARD_LOCATION = "Seam 2, Main Gallery"

CANONICAL_RISK_SCORE = 74.2
CANONICAL_RISK_LEVEL = "HIGH"
